# Permissions
# deluxecolors.colors.*: Access to the all chat colors
# deluxecolors.colors.<color>: Access to the specified chat color
#
# Color used in commands and feedback
Color:
  Main: '&6'
  Secondary: '&f'
#
# Settings
Default_Color: "Gray"
#
# Chat
Chat:
  Add_Color_To_Message: true
  Format:
    Override: false
    Format: "&f%player% >> %colorcode%%message%"
#
# Messages
Messages:
  No_Permission: "&7You don't have permission to use %colorcode%%colorname%&7!"
  Selected: "&7You have selected %colorcode%%colorname%&7!"
#
# UI
ColorPicker_UI:
  Title: "Pick a Chat Color"
  Locked:
  - "%colorcode%%colorname%"
  - "&7You have not unlocked the %colorcode%%colorname% &7chat color"
  Unlocked:
  - "%colorcode%%colorname%"
  - "&7Click to select the %colorcode%%colorname% &7chat color"
  On_Click:
    Always_Close: true
    Close_On_Change: true